name: Check Dead Links

on:
  push:
    branches:
      - master

jobs:
  dead-links:
    name: Dead Links Checker
    runs-on: ubuntu-latest
    steps:
      - name: Run Deadfinder
        uses: hahwul/deadfinder@1.3.3
        id: broken-link
        with:
          command: sitemap
          target: "https://demonkingswarn.is-a.dev/blog/sitemap.xml"
